return {
  { name = "a52dec", version = "0.0.0", summary = "A52 (AC-3) audio decoder lib" },
  { name = "abseil-cpp", version = "20260107", summary = "Google's Abseil C++ library (collection of C++ library code)" },
  { name = "acl", version = "1.1.2302", summary = "Access control list library" },
  { name = "adwaita-icon-theme", version = "50.0", summary = "Adwaita icon theme" },
  { name = "adwaita-icon-theme-legacy", version = "46.2", summary = "Full-color legacy icons for the Adwaita icon theme" },
  { name = "alacritty", version = "0.15.1", summary = "GPU-accelerated terminal emulator" },
  { name = "alsa-lib", version = "1.2.14", summary = "ALSA sound library (libasound)" },
  { name = "aquamarine", version = "0.12.0", summary = "Lightweight Wayland compositor library" },
  { name = "at-spi2-core", version = "2.56.1", summary = "Assistive Technology Service Provider Interface (includes ATK)" },
  { name = "atkmm", version = "2.36.4", summary = "C++ bindings for ATK accessibility toolkit" },
  { name = "avahi", version = "0.8", summary = "mDNS/DNS-SD (Bonjour) implementation" },
  { name = "awww", version = "0.12.1", summary = "Efficient animated wallpaper daemon for Wayland" },
  { name = "bat", version = "0.26.1", summary = "A cat clone with wings." },
  { name = "bitstreamvera", version = "1.10", summary = "Bitstream Vera TrueType fonts" },
  { name = "brotli", version = "1.2.0", summary = "Brotli compression library" },
  { name = "btop", version = "1.4.7", summary = "Resource monitor (bpytop ported to C++)" },
  { name = "bubblewrap", version = "0.11.2", summary = "Low-level unprivileged sandboxing tool (used by Flatpak)" },
  { name = "bzip2", version = "1.0.8", summary = "bzip2 compression library" },
  { name = "cairo", version = "1.18.4", summary = "2D graphics library with Xlib/XCB surfaces" },
  { name = "cairomm", version = "1.15.4", summary = "C++ bindings for the Cairo graphics library" },
  { name = "caja", version = "1.28.0", summary = "MATE file manager" },
  { name = "cava", version = "1.0.0", summary = "Console-based audio visualizer for ALSA, PulseAudio and PipeWire" },
  { name = "cjson", version = "1.7.19", summary = "Ultralightweight JSON parser for C (used by mango)" },
  { name = "curl", version = "8.14.1", summary = "URL retrieval tool" },
  { name = "clang21", version = "21.1.8", summary = "C language family frontend for LLVM 21 (clang and libclang-cpp)" },
  { name = "cmake", version = "3.31.6", summary = "Cross-platform build system generator" },
  { name = "cmatrix", version = "2.0", summary = "C Matrix (The Matrix) terminal screen saver" },
  { name = "compiler-rt", version = "22.1.8", summary = "Compiler runtime libraries for clang 22 (compiler-rt builtins)" },
  { name = "compiler-rt21", version = "21.1.8", summary = "Compiler runtime libraries for clang 21 (compiler-rt builtins)" },
  { name = "composefs", version = "1.0.8", summary = "Composable, immutable, content-addressed filesystem (and library)" },
  { name = "cowsay", version = "3.8.4", summary = "Cow says things" },
  { name = "cpio", version = "2.15", summary = "GNU cpio: a program to manage archives of files" },
  { name = "ctwm", version = "4.1.0", summary = "Window manager based on TWM (with virtual workspaces)" },
  { name = "dav1d", version = "1.5.4", summary = "AV1 cross-platform decoder library" },
  { name = "dbus", version = "1", summary = "D-Bus message bus (provided by the base system; stub package)" },
  { name = "dbus-glib", version = "0.112", summary = "GLib integration for the freedesktop D-Bus message bus" },
  { name = "dejavusans", version = "2.37", summary = "DejaVu Sans/Serif/Mono TrueType fonts" },
  { name = "discord", version = "1.0.152", summary = "Discord (stable Electron client)" },
  { name = "doas", version = "6.8.2", summary = "Execute commands as another user (portable OpenBSD doas)" },
  { name = "double-conversion", version = "3.4.0", summary = "IEEE-754 binary/decimal conversion library" },
  { name = "driftwm", version = "0.17.3", summary = "Trackpad-first infinite canvas Wayland compositor (smithay)" },
  { name = "egl", version = "1.5", summary = "EGL interface library (stub pkgconfig for libglvnd EGL)" },
  { name = "eom", version = "1.28.0", summary = "Eye of MATE image viewer" },
  { name = "equibop", version = "3.2.2", summary = "Discord client mod (Equicord, Electron app)" },
  { name = "exo", version = "4.20.0", summary = "Application development library for Xfce" },
  { name = "expat", version = "2.8.1", summary = "XML parsing C library" },
  { name = "extra-cmake-modules", version = "6.14.0", summary = "Extra CMake modules for KF6/LXQt builds" },
  { name = "faad2", version = "2.11.2", summary = "AAC decoder library" },
  { name = "fastfetch", version = "2.66.0", summary = "Fast, feature-rich system information fetcher (neofetch successor)" },
  { name = "fd", version = "10.2.0", summary = "Simple find alternative" },
  { name = "femboysay", version = "0.1.0", summary = "an intuitive tool, for them" },
  { name = "fetch", version = "2.3.0", summary = "Animated 3D fetch tool for your terminal" },
  { name = "fftw3", version = "3.3.11", summary = "Fastest Fourier Transform in the West (double precision)" },
  { name = "file", version = "5.46", summary = "File type identification library (libmagic)" },
  { name = "firefox", version = "153.0.3", summary = "Mozilla Firefox web browser (standalone build)" },
  { name = "fish", version = "4.8.1", summary = "Friendly interactive shell" },
  { name = "flac", version = "11.0.0", summary = "FLAC lossless audio codec" },
  { name = "flatpak", version = "1.18.0", summary = "Linux application sandboxing and distribution framework" },
  { name = "fmt", version = "11.1.4", summary = "Modern C++ formatting library" },
  { name = "fontconfig", version = "2.18.2", summary = "Font configuration and customization library" },
  { name = "freetype", version = "2.14.3", summary = "FreeType font engine library" },
  { name = "fribidi", version = "1.0.16", summary = "Bidirectional text algorithm library" },
  { name = "fvwm3", version = "1.1.5", summary = "Virtual window manager for the X Window System" },
  { name = "garcon", version = "4.20.0", summary = "Freedesktop.org menu library for Xfce" },
  { name = "gcc-libs", version = "15.2", summary = "GCC support libraries (libgomp, libgcc_s, libstdc++)" },
  { name = "gdk-pixbuf", version = "2.42.12", summary = "Image loading and scaling library" },
  { name = "git", version = "2.50.0", summary = "Distributed version control system" },
  { name = "glib", version = "2.88.1", summary = "GLib utility library, GObject, and GIO" },
  { name = "glibmm", version = "2.80.1", summary = "C++ bindings for GLib" },
  { name = "glslang", version = "1.4.357", summary = "GLSL/HLSL to SPIR-V compiler and validator" },
  { name = "glycin", version = "2.1.5", summary = "Sandboxed and extendable image decoding" },
  { name = "gmp", version = "10.5.0", summary = "GNU multiple precision arithmetic" },
  { name = "gnupg", version = "2.5.21", summary = "The GNU Privacy Guard — GnuPG encryption and signing tool" },
  { name = "gnutls", version = "30.42.0", summary = "TLS library" },
  { name = "gobject-introspection", version = "1.84.0", summary = "GObject introspection scanner and typelib library" },
  { name = "gpgme", version = "2.1.0", summary = "Library providing access to GnuPG crypto functions" },
  { name = "graphene", version = "1.10.8", summary = "Thin layer of math types for graphic libraries (required by GTK4)" },
  { name = "graphite2", version = "1.3.14", summary = "Graphite2 font rendering engine" },
  { name = "gsettings-desktop-schemas", version = "50.1", summary = "GSettings schemas for the GNOME/MATE desktop" },
  { name = "gtk-layer-shell", version = "0.10.1", summary = "GTK Wayland layer-shell bindings" },
  { name = "gtk3", version = "3.24.50", summary = "GTK+ 3 toolkit" },
  { name = "gtk4", version = "4.14.5", summary = "GTK+ 4 toolkit (X11 + Wayland)" },
  { name = "gtkmm3", version = "3.24.7", summary = "C++ bindings for GTK+ 3" },
  { name = "gtkmm4", version = "4.14.0", summary = "C++ bindings for GTK+ 4" },
  { name = "gtksourceview4", version = "4.8.4", summary = "GTK3 source code highlighting widget library" },
  { name = "gzip", version = "1.13", summary = "GNU gzip compression utilities" },
  { name = "harfbuzz", version = "11.1.0", summary = "Text shaping library" },
  { name = "hello", version = "1.0", summary = "A tiny demonstration package for Zeta" },
  { name = "hicolor-icon-theme", version = "0.18", summary = "Default fallback icon theme for XDG icon themes" },
  { name = "htop", version = "3.5.2", summary = "Interactive process viewer" },
  { name = "hwdata", version = "0.389", summary = "Hardware identification databases (pci.ids, usb.ids)" },
  { name = "hyprcursor", version = "0.1.13", summary = "Library and toolkit for the Hyprland cursor format" },
  { name = "hyprgraphics", version = "0.5.1", summary = "Hyprland graphics libraries" },
  { name = "hypridle", version = "0.1.8", summary = "Hyprland idle management daemon" },
  { name = "hyprland", version = "0.56.2", summary = "Dynamic tiling Wayland compositor" },
  { name = "hyprland-protocols", version = "0.7.0", summary = "Wayland protocol files for Hyprland" },
  { name = "hyprlang", version = "0.6.8", summary = "Hyprland config language parser library" },
  { name = "hyprpaper", version = "0.8.4", summary = "Hyprland wallpaper utility" },
  { name = "hyprtoolkit", version = "0.5.4", summary = "Hyprland toolkit library" },
  { name = "hyprutils", version = "0.14.0", summary = "Utility library for the Hypr ecosystem" },
  { name = "hyprwayland-scanner", version = "0.4.6", summary = "Hyprland Wayland protocol code generator" },
  { name = "hyprwire", version = "0.3.1", summary = "Wire format library for the Hypr ecosystem" },
  { name = "icu", version = "78.3", summary = "International Components for Unicode (libicui18n/libicuuc/libicudata), required by Qt 5" },
  { name = "imlib2", version = "1.12.6", summary = "Image loading and rendering library" },
  { name = "iniparser", version = "4.2.6", summary = "Standalone ini-file parsing library" },
  { name = "intel-full", version = "1.0", summary = "Complete Intel GPU graphics stack (VA-API iHD/i965, X11 DDX driver, Mesa)" },
  { name = "intel-gmmlib", version = "22.10.1", summary = "Intel Graphics Memory Management Library" },
  { name = "intel-media-driver", version = "26.2.4", summary = "Intel Media Driver for VA-API (iHD) — hardware video decode/encode for Gen8+" },
  { name = "iso-codes", version = "4.18.0", summary = "ISO language, region, script and currency code lists" },
  { name = "json-c", version = "0.18.0", summary = "JSON library" },
  { name = "jsoncpp", version = "1.9.6", summary = "C++ JSON reader/writer" },
  { name = "kidletime", version = "6.14.0", summary = "KF6 idle time detection (KF6IdleTime)" },
  { name = "kitty", version = "0.48.2", summary = "Fast, feature-rich, GPU-based terminal emulator" },
  { name = "kwindowsystem", version = "6.13.0", summary = "KDE Frameworks 6 window system library" },
  { name = "labwc", version = "0.20.1", summary = "wlroots-based Wayland compositor inspired by Openbox" },
  { name = "larp", version = "1.0.0", summary = "A simple script that displays a larp ASCII image" },
  { name = "layer-shell-qt", version = "6.4.0", summary = "Qt Wayland layer-shell interface library" },
  { name = "lcms2", version = "2.17", summary = "Little CMS 2 — color management library" },
  { name = "leancrypto", version = "1.0", summary = "Lean cryptography library" },
  { name = "less", version = "704", summary = "GNU less pager" },
  { name = "libICE", version = "1.1.2", summary = "X Inter-Client Exchange library" },
  { name = "libSM", version = "1.2.5", summary = "X Session Management library" },
  { name = "libX11", version = "1.8.13", summary = "X11 core client library" },
  { name = "libXau", version = "1.0.12", summary = "X authorization protocol library (X11)" },
  { name = "libXaw", version = "1.0.16", summary = "X11 Athena Widget set" },
  { name = "libXcomposite", version = "0.4.7", summary = "X11 Composite extension client library" },
  { name = "libXcursor", version = "1.2.3", summary = "X11 cursor management and image loading library" },
  { name = "libXdamage", version = "1.1.7", summary = "X11 Damage extension client library" },
  { name = "libXdmcp", version = "1.1.5", summary = "X Display Manager Control Protocol library (X11)" },
  { name = "libXext", version = "1.3.7", summary = "X11 miscellaneous extension library (Xext, MIT-SHM, DBE, etc.)" },
  { name = "libXfixes", version = "6.0.2", summary = "X11 XFixes extension client library" },
  { name = "libXfont2", version = "2.0.9", summary = "X11 font rasterization and font server client library" },
  { name = "libXft", version = "2.3.9", summary = "X11 FreeType-based font rendering library" },
  { name = "libXi", version = "1.8.2", summary = "X11 Input extension library" },
  { name = "libXinerama", version = "1.1.6", summary = "X11 Xinerama extension client library" },
  { name = "libXkbfile", version = "1.1.3", summary = "X11 XKB file manipulation library" },
  { name = "libXmu", version = "1.3.1", summary = "X11 miscellaneous utilities library (incl. libXmuu)" },
  { name = "libXpm", version = "3.5.19", summary = "X11 pixmap (XPM) image format library" },
  { name = "libXpresent", version = "1.0.1", summary = "X11 Present extension" },
  { name = "libXrandr", version = "1.5.5", summary = "X11 RandR extension client library" },
  { name = "libXrender", version = "0.9.12", summary = "X Render extension client library (X11)" },
  { name = "libXres", version = "1.2.2", summary = "X11 resource usage extension" },
  { name = "libXt", version = "1.3.1", summary = "X11 toolkit intrinsics library" },
  { name = "libXtst", version = "1.2.5", summary = "X11 Testing extension library" },
  { name = "libXv", version = "1.0.13", summary = "X11 Video extension library" },
  { name = "libXvMC", version = "1.0.14", summary = "X Video Motion Compensation extension library" },
  { name = "libXxf86vm", version = "1.1.7", summary = "X11 XFree86 video mode extension library" },
  { name = "libappstream", version = "1.1.5", summary = "AppStream cross-distro software metadata library" },
  { name = "libarchive", version = "3.8.9", summary = "Library for reading/writing streaming archives" },
  { name = "libassuan", version = "3.0.2", summary = "IPC library used by GnuPG components" },
  { name = "libb2", version = "0.98.1", summary = "BLAKE2 hash function library" },
  { name = "libcanberra", version = "0.30", summary = "XDG Sound Theme and Name Specifications implementation" },
  { name = "libcups", version = "2.4.19", summary = "CUPS printing library (libcups.so.2)" },
  { name = "libcurl", version = "8.21.0", summary = "URL transfer library" },
  { name = "libdaemon", version = "0.14", summary = "Lightweight C library for writing daemons" },
  { name = "libdbusmenu-lxqt", version = "0.2.0", summary = "LXQt dbusmenu library" },
  { name = "libdconf", version = "0.40.0", summary = "GSettings configuration backend" },
  { name = "libdisplay-info", version = "0.3.0", summary = "EDID and DisplayID library" },
  { name = "libdrm", version = "2.4.134", summary = "Direct Rendering Manager userspace library" },
  { name = "libebml", version = "5.0.0", summary = "EBML container library" },
  { name = "libedit", version = "20260512_3.1", summary = "Command line editor library providing generic line editing, history, and tokenization functions" },
  { name = "libei", version = "1.6.0", summary = "Library for Emulated Input (libei + libeis)" },
  { name = "libepoxy", version = "1.5.10", summary = "Thin wrapper around modern GL/EGL dispatch" },
  { name = "libevdev", version = "1.13.6", summary = "Wrapper library for evdev devices" },
  { name = "libevent", version = "2.1.12", summary = "Event notification library" },
  { name = "libexif", version = "0.6.24", summary = "EXIF parsing library" },
  { name = "libffi", version = "3.4.6", summary = "Portable Foreign Function Interface library" },
  { name = "libfm", version = "1.4.1", summary = "File manager library" },
  { name = "libfm-extra", version = "1.3.2", summary = "File-manager helper library (libfm-extra)" },
  { name = "libfm-gtk3", version = "1.4.1", summary = "GTK3 bindings for libfm" },
  { name = "libfm-qt", version = "2.1.0", summary = "Qt6 file-manager library" },
  { name = "libfontenc", version = "1.1.9", summary = "X11 font encoding library" },
  { name = "libfuse3", version = "3.18.2", summary = "Filesystem in Userspace library (FUSE 3)" },
  { name = "libfyaml", version = "0.9", summary = "Fully featured YAML 1.2 parser and emitter" },
  { name = "libgcrypt", version = "1.12.2", summary = "GNU Cryptographic Library" },
  { name = "libgit2", version = "1.9.7", summary = "Library implementing Git core methods (used by cargo)" },
  { name = "libglvnd", version = "1.7.0", summary = "Vendor-neutral GL/GLX/EGL dispatch library" },
  { name = "libgpg-error", version = "1.61", summary = "Library defining common GnuPG error values" },
  { name = "libgtop", version = "2.41.3", summary = "Library for system information via /proc (libgtop-2.0)" },
  { name = "libgudev", version = "238", summary = "GObject bindings for libudev" },
  { name = "libhwy", version = "1.2.0", summary = "Google Highway SIMD library" },
  { name = "libigdgmm", version = "22.5.0", summary = "Intel Graphics Memory Management Library" },
  { name = "libidn2", version = "0.4.0", summary = "Internationalized domain names" },
  { name = "libinput", version = "1.31.3", summary = "Input device and event processing library" },
  { name = "libjpeg-turbo", version = "3.2.0", summary = "MMX/SSE2/SMID accelerated library for manipulating JPEG images" },
  { name = "libjson-glib", version = "1.10.0", summary = "GLib-based JSON serialization library" },
  { name = "libjxl", version = "0.11.1", summary = "JPEG XL image format library" },
  { name = "libksba", version = "1.8.0", summary = "Library for X.509 and CMS data structures" },
  { name = "liblxqt", version = "2.1.0", summary = "Core LXQt library" },
  { name = "libmatekbd", version = "1.28.0", summary = "MATE keyboard configuration library" },
  { name = "libmateweather", version = "1.28.0", summary = "MATE library to access weather information" },
  { name = "libmatroska", version = "7.0.0", summary = "Matroska container library" },
  { name = "libmtdev", version = "1.1.6", summary = "Multitouch protocol translation library (mtdev)" },
  { name = "libnl", version = "3.11.0", summary = "Netlink protocol library" },
  { name = "libnotify", version = "0.8.8", summary = "Desktop notification library" },
  { name = "libogg", version = "0.8.6", summary = "Ogg bitstream library" },
  { name = "libostree", version = "2025.7", summary = "Content-addressed object storage and versioning (ostree)" },
  { name = "libpciaccess", version = "0.17", summary = "Generic PCI access library (X11)" },
  { name = "libpeas", version = "1.36.0", summary = "GObject plugins library (with libpeas-gtk)" },
  { name = "libpng", version = "1.6.47", summary = "PNG image format library" },
  { name = "libpsl", version = "0.21.5", summary = "Public Suffix List library" },
  { name = "libqtxdg", version = "4.1.0", summary = "Qt6 XDG integration library" },
  { name = "libreoffice", version = "26.2.4.2", summary = "LibreOffice office suite (core, shared data, help)" },
  { name = "libreoffice-core", version = "26.2.4.2", summary = "LibreOffice runtime (soffice, VCL, bundled libs)" },
  { name = "libreoffice-help", version = "26.2.4.2", summary = "LibreOffice offline help" },
  { name = "libreoffice-share", version = "26.2.4.2", summary = "LibreOffice shared data (templates, config, gallery)" },
  { name = "librsvg", version = "2.60.0", summary = "SVG rendering library (rsvg)" },
  { name = "libseccomp", version = "2.6.0", summary = "High-level interface to the Linux seccomp syscall filter" },
  { name = "libshout", version = "3.2.0", summary = "Icecast streaming library" },
  { name = "libsigc++", version = "3.6.0", summary = "Typesafe callback framework for C++" },
  { name = "libsigc++2", version = "2.10.8", summary = "Typesafe callback framework for C++ (sigc++ 2.x ABI)" },
  { name = "libsndfile", version = "1.2.2", summary = "Library for reading and writing audio files" },
  { name = "libsoup2", version = "2.74.3", summary = "HTTP client/server library for GNOME (libsoup 2.x)" },
  { name = "libsoup3", version = "3.6.6", summary = "HTTP client/server library for GNOME (libsoup 3)" },
  { name = "libssh2", version = "1.11.1", summary = "Library implementing the SSH2 protocol" },
  { name = "libtasn1", version = "6.6.5", summary = "ASN.1 library" },
  { name = "libtdb", version = "1.4.12", summary = "Trivial database (key-value store) library" },
  { name = "libthai", version = "0.1.29", summary = "Thai language support library (libthai, libdatrie)" },
  { name = "libtheora", version = "2.2.1", summary = "Theora video codec" },
  { name = "libtinfo", version = "6.6", summary = "Terminfo database and terminal capability library" },
  { name = "libtirpc", version = "1.3.6", summary = "Transport Independent RPC library" },
  { name = "libudev", version = "1", summary = "udev library (provided by the base system; stub package)" },
  { name = "libunistring", version = "5.2.1", summary = "Unicode string library" },
  { name = "libuuid", version = "2.42.1", summary = "UUID library (from util-linux)" },
  { name = "libva", version = "2.2300.0", summary = "Video Acceleration API" },
  { name = "libva-intel-driver", version = "2.4.1", summary = "Intel VA-API driver for i965 (pre-Broadwell legacy driver)" },
  { name = "libvorbis", version = "3.3.8", summary = "Vorbis audio codec" },
  { name = "libvpx", version = "12.0.0", summary = "VP8/VP9 video codec" },
  { name = "libwacom", version = "2.19.0", summary = "Wacom tablet database and library" },
  { name = "libwebp", version = "1.5.0", summary = "WebP image codec library" },
  { name = "libwnck3", version = "43.3", summary = "Window Navigator Construction Kit (GTK3)" },
  { name = "libxcb", version = "1.17.0", summary = "X C Binding library (X11 protocol client library)" },
  { name = "libxcb-xrm", version = "1.3", summary = "X resource manager extension" },
  { name = "libxcvt", version = "0.1.3", summary = "Library for VESA CVT standard timing modelines" },
  { name = "libxfce4ui", version = "4.20.0", summary = "Widgets library for the Xfce UI" },
  { name = "libxfce4util", version = "4.20.1", summary = "Basic utility library for Xfce" },
  { name = "libxfce4windowing", version = "4.20.6", summary = "X11 and Wayland windowing library for Xfce" },
  { name = "libxklavier", version = "5.4", summary = "X Keyboard Extension querying/manipulation library" },
  { name = "libxml2", version = "2.15.3", summary = "XML C parser and toolkit" },
  { name = "libxmlb", version = "0.3.23", summary = "Library to help create and query binary XML blobs" },
  { name = "libxshmfence", version = "1.3.3", summary = "X shared-memory fence sync primitives" },
  { name = "libxss", version = "1.2.3", summary = "X11 Screen Saver extension library" },
  { name = "libyaml", version = "0.2.5", summary = "YAML 1.1 parser and emitter library" },
  { name = "libz", version = "1.3.2", summary = "Zlib compression library" },
  { name = "libzip", version = "1.11.4", summary = "C library for reading, creating, and modifying zip archives" },
  { name = "libzstd", version = "1.5.7", summary = "Zstandard - Fast real-time compression algorithm" },
  { name = "lld", version = "22.1.8", summary = "LLVM 22 linker (lld libraries and tooling)" },
  { name = "lld21", version = "21.1.8", summary = "LLVM 21 linker (lld libraries and tooling)" },
  { name = "llhttp", version = "9.3.1", summary = "Portable, incremental HTTP/1.1 parser (used by libgit2)" },
  { name = "llvm-libs", version = "22.1.8", summary = "LLVM runtime libraries (libLLVM-22.so)" },
  { name = "llvm-mingw", version = "20260616", summary = "LLVM/Clang/LLD based MinGW-w64 cross toolchain" },
  { name = "llvm21-libs", version = "21.1.8", summary = "LLVM 21 runtime libraries (libLLVM-21.so)" },
  { name = "lm-sensors", version = "3.6.2", summary = "Hardware sensors monitoring library (libsensors)" },
  { name = "lua", version = "5.5.1", summary = "Lua 5.5 scripting language interpreter" },
  { name = "lua51", version = "5.1.5", summary = "Lua 5.1 interpreter library" },
  { name = "luajit", version = "2.1.1785763465", summary = "Just-in-time compiler and drop-in replacement for Lua 5.1" },
  { name = "luv", version = "1.52.1-0", summary = "libuv bindings for LuaJIT" },
  { name = "lxde", version = "0.1.0", summary = "LXDE desktop environment (meta-package)" },
  { name = "lxappearance", version = "0.6.4", summary = "LXDE GTK theme switcher" },
  { name = "lxmenu-data", version = "0.1.5", summary = "Freedesktop menu definitions for LXDE" },
  { name = "lxpanel", version = "0.10.1", summary = "LXDE desktop panel" },
  { name = "lxsession", version = "0.5.1", summary = "LXDE session manager" },
  { name = "lxqt", version = "2.1.0", summary = "LXQt desktop group (meta-package)" },
  { name = "lxqt-about", version = "2.1.0", summary = "LXQt component (lxqt-about)" },
  { name = "lxqt-build-tools", version = "2.1.0", summary = "LXQt build-tools for CMake" },
  { name = "lxqt-config", version = "2.1.0", summary = "LXQt component (lxqt-config)" },
  { name = "lxqt-globalkeys", version = "2.1.0", summary = "LXQt component (lxqt-globalkeys)" },
  { name = "lxqt-menu-data", version = "2.1.0", summary = "LXQt menu configuration data" },
  { name = "lxqt-notificationd", version = "2.1.0", summary = "LXQt component (lxqt-notificationd)" },
  { name = "lxqt-panel", version = "2.1.0", summary = "LXQt component (lxqt-panel)" },
  { name = "lxqt-policykit", version = "2.1.0", summary = "LXQt component (lxqt-policykit)" },
  { name = "lxqt-powermanagement", version = "2.1.0", summary = "LXQt component (lxqt-powermanagement)" },
  { name = "lxqt-qtplugin", version = "2.1.0", summary = "LXQt component (lxqt-qtplugin)" },
  { name = "lxqt-runner", version = "2.1.0", summary = "LXQt component (lxqt-runner)" },
  { name = "lxqt-session", version = "2.1.1", summary = "LXQt component (lxqt-session)" },
  { name = "lxqt-themes", version = "2.1.0", summary = "LXQt component (lxqt-themes)" },
  { name = "ly", version = "1.0.3", summary = "TUI display manager (pam + xcb)" },
  { name = "lz4", version = "1.10.0", summary = "LZ4 compression library" },
  { name = "make", version = "4.4.1", summary = "GNU Make — build automation tool" },
  { name = "mango", version = "0.15.6", summary = "MangoWM: lightweight dwl-based Wayland compositor" },
  { name = "marco", version = "1.28.1", summary = "MATE window manager" },
  { name = "mate", version = "1.28", summary = "MATE desktop group (meta-package)" },
  { name = "mate-backgrounds", version = "1.28.0", summary = "MATE desktop background wallpapers" },
  { name = "mate-calc", version = "1.28.0", summary = "MATE calculator" },
  { name = "mate-control-center", version = "1.28.0", summary = "MATE control center" },
  { name = "mate-desktop", version = "1.28.2", summary = "MATE desktop library and GSettings schemas" },
  { name = "mate-icon-theme", version = "1.28.0", summary = "MATE default icon theme" },
  { name = "mate-menus", version = "1.28.0", summary = "MATE menu system" },
  { name = "mate-notification-daemon", version = "1.28.3", summary = "MATE notification daemon" },
  { name = "mate-panel", version = "1.28.4", summary = "MATE desktop panel" },
  { name = "mate-polkit", version = "1.28.1", summary = "MATE PolicyKit authentication agent" },
  { name = "mate-power-manager", version = "1.28.1", summary = "MATE power manager" },
  { name = "mate-session-manager", version = "1.28.0", summary = "MATE session manager" },
  { name = "mate-settings-daemon", version = "1.28.0", summary = "MATE settings daemon" },
  { name = "mate-terminal", version = "1.28.1", summary = "MATE terminal" },
  { name = "mate-utils", version = "1.28.0", summary = "MATE system utilities" },
  { name = "md4c", version = "0.5.3", summary = "C Markdown parser library" },
  { name = "menu-cache", version = "1.1.1", summary = "LXDE menu cache library" },
  { name = "mesa-drivers", version = "26.1.8", summary = "Intel + AMD OpenGL, Vulkan, and VA-API drivers (Mesa 26.1.8)" },
  { name = "mesa-full", version = "1.0", summary = "Complete Mesa graphics stack (OpenGL, EGL, GBM, DRI drivers, VA-API, Vulkan loader)" },
  { name = "micro", version = "2.0.15", summary = "Modern and intuitive terminal-based text editor" },
  { name = "mksh", version = "R59c", summary = "MirBSD Korn Shell" },
  { name = "mm-common", version = "1.0.8", summary = "Common build infrastructure for Gtkmm projects" },
  { name = "mpc", version = "1.3.1", summary = "GNU Multiple Precision Complex Library" },
  { name = "mpfr", version = "4.2.1", summary = "GNU multiple-precision floating-point rounding library" },
  { name = "mpg123", version = "0.49.4", summary = "MPEG audio decoder library" },
  { name = "muparser", version = "2.3.5", summary = "Fast math expression parser library" },
  { name = "ncurses", version = "6.6", summary = "System V Release 4.0 curses library (libncursesw runtime)" },
  { name = "neovim", version = "0.12.4", summary = "Vim-fork focused on extensibility and usability" },
  { name = "nettle", version = "1.0", summary = "Cryptographic library" },
  { name = "nghttp2", version = "1.70.0", summary = "HTTP/2 framing layer C library" },
  { name = "npth", version = "1.8", summary = "New Portable Threads library" },
  { name = "nscde", version = "2.3", summary = "Not so Common Desktop Environment: retro CDE-like desktop on FVWM" },
  { name = "nss", version = "3.124", summary = "Network Security Services (libnss3/libnspr4 runtime)" },
  { name = "ntbtls", version = "0.3.2", summary = "A small TLS library using Libgcrypt and Libksba" },
  { name = "nvidia", version = "595.71.05", summary = "NVIDIA official driver (meta-package: open kernel modules + userspace)" },
  { name = "nvidia-compiler", version = "595.71.05", summary = "NVIDIA official driver compiler libraries (NVVM, gpucomp, tileiras)" },
  { name = "nvidia-cuda", version = "595.71.05", summary = "NVIDIA official driver CUDA/OpenCL runtime (libcuda, libOpenCL, MPS tools)" },
  { name = "nvidia-firmware", version = "595.71.05", summary = "NVIDIA official driver GSP firmware (loaded by the open kernel modules)" },
  { name = "nvidia-kernel", version = "595.71.05", summary = "NVIDIA official open GPU kernel modules (compiled against the running kernel at install time)" },
  { name = "nvidia-optix", version = "595.71.05", summary = "NVIDIA official driver OptiX runtime (libnvoptix, rtcore)" },
  { name = "nvidia-utils", version = "595.71.05", summary = "NVIDIA official driver userspace (vendor GL/EGL/GLES/Vulkan libs, tools, Xorg modules)" },
  { name = "openbox", version = "3.6.1", summary = "Openbox X11 window manager (LXQt default WM)" },
  { name = "opencode", version = "1.18.18", summary = "AI-powered CLI coding agent" },
  { name = "openssh", version = "10.3p1", summary = "OpenSSH protocol implementation for remote login, command execution and file transfer" },
  { name = "openssl", version = "3.6.3", summary = "OpenSSL 3 crypto and TLS libraries (libcrypto/libssl)" },
  { name = "opsec", version = "1.0.0", summary = "opsec" },
  { name = "opus", version = "0.11.1", summary = "Opus audio codec" },
  { name = "p11-kit", version = "0.4.8", summary = "PKCS#11 module loading library" },
  { name = "pam", version = "1", summary = "Pluggable Authentication Modules (provided by the base system; stub package)" },
  { name = "pango", version = "1.56.3", summary = "Text layout and rendering library" },
  { name = "pangomm", version = "2.54.0", summary = "C++ bindings for Pango" },
  { name = "pcmanfm", version = "2.1.0", summary = "Lightweight GTK3 file manager" },
  { name = "pcmanfm-qt", version = "2.1.0", summary = "LXQt component (pcmanfm-qt)" },
  { name = "pcre2", version = "10.47", summary = "Perl-compatible regular expression library v2" },
  { name = "pinentry", version = "1.3.3", summary = "PIN or passphrase entry dialog for GnuPG" },
  { name = "pipewire", version = "1.6.8", summary = "Multimedia processing graph and audio/video daemon" },
  { name = "pixman", version = "0.46.4", summary = "Pixel manipulation library (low-level rendering primitives)" },
  { name = "plasma-wayland-protocols", version = "1.17.0", summary = "KDE Wayland protocol XML (build-dep of kidletime)" },
  { name = "pluma", version = "1.28.0", summary = "MATE text editor" },
  { name = "polkit", version = "127", summary = "Authorization framework for desktop privileges" },
  { name = "polkit-qt-1", version = "0.200.0", summary = "Qt6 polkit wrapper library" },
  { name = "procps-ng", version = "4.0.7rc1", summary = "libproc2 process information library" },
  { name = "pugixml", version = "1.15", summary = "Lightweight C++ XML processing library" },
  { name = "pulseaudio", version = "17.0", summary = "Network-capable sound server and client library" },
  { name = "qt5", version = "5.15.19", summary = "Qt 5 runtime libraries (Core/Gui/Widgets/Svg/X11Extras/XcbQpa + plugins)" },
  { name = "qtbase", version = "6.8.2", summary = "Qt 6 base libraries" },
  { name = "qtdeclarative", version = "6.8.2", summary = "Qt6 QML/Quick modules" },
  { name = "qterminal", version = "2.1.0", summary = "LXQt terminal emulator (Qt6, QTermWidget)" },
  { name = "qtermwidget", version = "2.1.0", summary = "QTermWidget terminal emulator widget library (Qt6)" },
  { name = "qtshadertools", version = "6.8.2", summary = "Qt6 shader tools module" },
  { name = "qtsvg", version = "6.8.2", summary = "Qt 6 SVG module" },
  { name = "qttools", version = "6.8.2", summary = "Qt 6 tools (linguist, qdbus, qtpaths)" },
  { name = "qtwayland", version = "6.8.2", summary = "Qt6 Wayland platform plugin" },
  { name = "re2", version = "2025.11.05", summary = "Efficient regular expression library (Google)" },
  { name = "ripgrep", version = "14.1.1", summary = "Recursive grep alternative" },
  { name = "rofi", version = "1.7.8", summary = "Window switcher, application launcher and dmenu replacement" },
  { name = "rsync", version = "3.4.1", summary = "Remote file sync" },
  { name = "rust", version = "1.98.0", summary = "Systems programming language (rustc, cargo, rustfmt, clippy, rustdoc)" },
  { name = "scenefx", version = "0.5", summary = "Wayland compositor effects library (window animation/effects)" },
  { name = "sdbus-cpp", version = "2.3.1", summary = "C++ wrapper library for sd-bus (libsystemd D-Bus client)" },
  { name = "sdl2", version = "2.32.10", summary = "Simple DirectMedia Layer 2 (low-level multimedia library)" },
  { name = "seatd", version = "0.9.3", summary = "Seat management daemon and library" },
  { name = "setxkbmap", version = "1.3.2", summary = "Set the keyboard using the X Keyboard Extension" },
  { name = "shared-mime-info", version = "2.5.1", summary = "Freedesktop.org shared MIME database and update-mime-database" },
  { name = "solid", version = "6.14.0", summary = "KF6 hardware detection (KF6Solid)" },
  { name = "spdlog", version = "1.15.3", summary = "Fast C++ logging library" },
  { name = "speex", version = "1.5.2", summary = "Speex audio codec" },
  { name = "spirv-tools", version = "2026.2.1", summary = "API for SPIR-V bytecode processing (libSPIRV-Tools)" },
  { name = "sqlite", version = "3.53.4", summary = "Self-contained, embeddable SQL database engine" },
  { name = "startup-notification", version = "0.12", summary = "X11 application startup notification library" },
  { name = "swaybg", version = "1.2.2", summary = "Wallpaper utility for Wayland compositors (sway)" },
  { name = "systemd-libs", version = "257", summary = "systemd libraries (libsystemd, libudev)" },
  { name = "taglib", version = "2.3.0", summary = "Audio metadata tag library" },
  { name = "tango-icon-theme", version = "0.8.90", summary = "Tango icon theme" },
  { name = "tar", version = "1.35", summary = "GNU tar: file archiver" },
  { name = "thunar", version = "4.20.9", summary = "File manager for Xfce" },
  { name = "tllist", version = "1.1.0", summary = "Typed Linked List C header library" },
  { name = "tomlplusplus", version = "3.4.0", summary = "Header-only TOML config file parser for C++17" },
  { name = "tree", version = "2.1.1", summary = "Display directories as trees" },
  { name = "tree-sitter", version = "0.26.9", summary = "Incremental parsing system for programming tools" },
  { name = "tslib", version = "1.24", summary = "Touchscreen input library (libts), used by Qt 5 touch plugins" },
  { name = "twolame", version = "0.0.0", summary = "MPEG-2 AAC encoder library" },
  { name = "unibilium", version = "2.1.2", summary = "Library to parse terminal information (terminfo)" },
  { name = "unimatrix", version = "master", summary = "Matrix-style digital rain for the terminal" },
  { name = "unzip", version = "6.0", summary = "InfoZIP extractor" },
  { name = "upower", version = "1.90.10", summary = "Power management daemon and tools" },
  { name = "util-linux-libs", version = "2.42", summary = "Util-linux shared libraries (libblkid, libmount)" },
  { name = "util-macros", version = "1.20.2", summary = "X.Org Autoconf macros (build-time dependency)" },
  { name = "vim", version = "9.2.0920", summary = "Modal text editor" },
  { name = "vlc", version = "3.0.23", summary = "VLC media player" },
  { name = "vte", version = "0.76.6", summary = "Terminal emulator widget library (GTK3)" },
  { name = "vulkan-headers", version = "1.3.296", summary = "Vulkan API headers" },
  { name = "vulkan-loader", version = "1.3.296", summary = "Vulkan ICD loader library" },
  { name = "waybar", version = "0.15.0", summary = "Highly customizable Wayland bar (Sway/Waybar)" },
  { name = "wayland", version = "1.26.0", summary = "Wayland compositor infrastructure: client/server libraries and scanner" },
  { name = "wayland-protocols", version = "1.49", summary = "Wayland protocol XML definitions (build-time data for compositors and clients)" },
  { name = "wget", version = "1.25.0", summary = "Network downloader" },
  { name = "which", version = "2.21", summary = "Locate a command in the PATH" },
  { name = "wine", version = "11.0", summary = "Compatibility layer for running Windows applications" },
  { name = "wlr-protocols", version = "1.14.0", summary = "wlr Wayland protocol definitions" },
  { name = "wlroots", version = "0.20.2", summary = "Modular Wayland compositor library" },
  { name = "wmaker", version = "0.96.0", summary = "Window Maker: GNUstep-compliant NeXTstep window manager clone" },
  { name = "wofi", version = "1.5.3", summary = "Wayland-native launcher (rofi-style)" },
  { name = "xauth", version = "1.1.5", summary = "X authority file utility (X11)" },
  { name = "xcb-proto", version = "1.17.0", summary = "XCB protocol descriptions (build-time dependency)" },
  { name = "xcb-util", version = "0.4.1", summary = "Base utilities library for XCB" },
  { name = "xcb-util-cursor", version = "0.1.6", summary = "XCB cursor utility library" },
  { name = "xcb-util-image", version = "0.4.1", summary = "XCB image utility library" },
  { name = "xcb-util-keysyms", version = "0.4.1", summary = "XCB keyboard shortcuts utility library" },
  { name = "xcb-util-renderutil", version = "0.3.10", summary = "XCB render utility library" },
  { name = "xcb-util-wm", version = "0.4.2", summary = "XCB EWMH and ICCCM utilities" },
  { name = "xdg-desktop-portal", version = "1.22.1", summary = "Desktop integration portal frontend (D-Bus)" },
  { name = "xdg-desktop-portal-hyprland", version = "1.4.1", summary = "Hyprland backend for xdg-desktop-portal (screen sharing, file picker)" },
  { name = "xdg-user-dirs", version = "0.18", summary = "XDG user dirs management tool" },
  { name = "xdpyinfo", version = "1.2.0", summary = "Display information utility for X" },
  { name = "xf86-input-libinput", version = "1.5.0", summary = "X.Org input driver based on libinput" },
  { name = "xf86-video-intel", version = "2.99.917", summary = "X.Org Intel DDX video driver" },
  { name = "xfce4", version = "4.20", summary = "Xfce desktop group (meta-package)" },
  { name = "xfce4-appfinder", version = "4.20.0", summary = "Xfce application finder" },
  { name = "xfce4-dev-tools", version = "4.20.0", summary = "Xfce development tools (xdt-autogen)" },
  { name = "xfce4-notifyd", version = "0.9.7", summary = "Notification daemon for Xfce with theming support" },
  { name = "xfce4-panel", version = "4.20.8", summary = "Xfce desktop panel" },
  { name = "xfce4-power-manager", version = "4.20.1", summary = "Power manager for Xfce" },
  { name = "xfce4-session", version = "4.20.4", summary = "Xfce session manager" },
  { name = "xfce4-settings", version = "4.20.5", summary = "Xfce settings manager and configuration dialogs" },
  { name = "xfce4-terminal", version = "1.2.0", summary = "Terminal emulator for Xfce" },
  { name = "xfconf", version = "4.20.0", summary = "Flexible, easy-to-use configuration management system for Xfce" },
  { name = "xfdesktop", version = "4.20.2", summary = "Xfce desktop background and icons manager" },
  { name = "xfwm4", version = "4.20.0", summary = "Xfce window manager with compositor" },
  { name = "xgamma", version = "1.0.8", summary = "Alter a monitor's gamma correction through the X server" },
  { name = "xinit", version = "1.4.4", summary = "X11 server startup tool (startx/xinit)" },
  { name = "xkbcommon", version = "1.13.2", summary = "Keyboard keymap compiler and support library" },
  { name = "xkbcomp", version = "1.4.7", summary = "X keyboard description compiler" },
  { name = "xkeyboard-config", version = "2.47", summary = "XKB keymap rules and symbols database" },
  { name = "xmessage", version = "1.0.7", summary = "Display a message or dialog in a window" },
  { name = "xmodmap", version = "1.0.12", summary = "Utility for modifying keymaps and pointer button mappings in X" },
  { name = "xorg-full", version = "21.1.24", summary = "Complete X.Org stack (meta-package): X server, X11/XCB libs, GL, input, fonts, utilities" },
  { name = "xorg-server", version = "21.1.24", summary = "X.Org X server (modesetting driver, GLX + glamor)" },
  { name = "xorgproto", version = "2025.1", summary = "Combined X.Org protocol headers (build-time dependency)" },
  { name = "xprop", version = "1.2.8", summary = "Property displayer for X" },
  { name = "xrandr", version = "1.5.4", summary = "X RandR extension display configuration tool" },
  { name = "xrdb", version = "1.2.3", summary = "X resource database utility" },
  { name = "xset", version = "1.2.6", summary = "User preference utility for X" },
  { name = "xshmfence", version = "1.3.3", summary = "X11 shared memory fence library (synchronization primitives)" },
  { name = "xterm", version = "410", summary = "X terminal emulator" },
  { name = "xtrans", version = "1.5.1", summary = "X transport library (headers and pkg-config file, build-time dependency)" },
  { name = "xwayland", version = "24.1.13", summary = "X server for Wayland" },
  { name = "xxhash", version = "0.8.3", summary = "Extremely fast non-cryptographic hash algorithm" },
  { name = "xz-utils", version = "5.6.4", summary = "XZ/LZMA compression (xz, lzma, liblzma)" },
  { name = "zig", version = "0.16.0", summary = "Zig compiler and toolchain (LLVM 21 backend, all features)" },
  { name = "zip", version = "3.0", summary = "InfoZIP archiver" },
  { name = "zsh", version = "5.9.2", summary = "Powerful shell with scripting and tab completion" },
  { name = "zstd", version = "1.5.7", summary = "Zstandard compression library" },
}
